name: Build

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    name: Build Windows Ndll
    runs-on: windows-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries
        run: |
          haxelib install lime --quiet
          haxelib install hxcpp --quiet

      - name: Compile Ndll
        run: haxelib run lime rebuild . windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TransparencyNdll-Windows
          path: ndll/Windows64/

      - name: Upload Artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: TransparencyNdll-Windows-x86
          path: ndll/Windows/

  buildLinux:
    name: Build Linux Ndll
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Libraries
        run: |
          sudo apt-get -qq install gcc-multilib g++-multilib
          haxelib install lime --quiet
          haxelib install hxcpp --quiet

      - name: Compile Ndll
        run: haxelib run lime rebuild . linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TransparencyNdll-Linux
          path: ndll/Linux64/

      - name: Upload Artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: TransparencyNdll-Linux-x86
          path: ndll/Linux/


  buildMacOS:
    name: Build MacOS Ndll
    runs-on: macos-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries
        run: |
          haxelib install lime --quiet
          haxelib install hxcpp --quiet

      - name: Compile Ndll
        run: haxelib run lime rebuild . mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TransparencyNdll-Mac
          path: ndll/MacArm64/
